services:
  app:
    container_name: aquagraph
    image: aquagraph:latest
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/app:cached
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    command: poetry run chainlit run src/app.py --host 0.0.0.0 --port 80 -h
    restart: unless-stopped