[project]
enable_telemetry = false
user_env = []
session_timeout = 3600
cache = false
allow_origins = ["*"]

[features]
unsafe_allow_html = false
latex = true
auto_tag_thread = true
edit_message = true

[features.spontaneous_file_upload]
enabled = true
accept = ["*/*"]
max_files = 20
max_size_mb = 500

[features.audio]
min_decibels = -45
initial_silence_timeout = 3000
silence_timeout = 1500
max_duration = 15000
chunk_duration = 1000
sample_rate = 44100

[UI]
name = "AquaPDF"
description = "Tu asistente AI para políticas y procedimientos de la empresa"
default_collapse_content = true
cot = "full"
custom_css = "public/custom.css"
custom_font = "https://fonts.googleapis.com/css2?family=Sora:wght@400;500;700&display=swap"

[UI.theme]
default = "dark"
font_family = "Sora, sans-serif"

[UI.theme.light]
background = "#FFFFFF"
paper = "#F5F9FB"

[UI.theme.light.primary]
main = "#006D8F"
dark = "#004D66"
light = "#E6F3F7"

[UI.theme.light.text]
primary = "#1A2B32"
secondary = "#4A6975"

[UI.theme.dark]
background = "#1A1A1A"
paper = "#242424"

[UI.theme.dark.primary]
main = "#0095C2"
dark = "#006D8F"
light = "#33B7DD"

[UI.theme.dark.text]
primary = "#F5F9FB"
secondary = "#88A5B3"

[meta]
generated_by = "1.3.2"
