[project]
enable_telemetry = false
user_env = []
session_timeout = 3600
cache = false
allow_origins = ["*"]

[features]
unsafe_allow_html = false
latex = true
auto_tag_thread = true
edit_message = true

[features.spontaneous_file_upload]
enabled = true
accept = ["*/*"]
max_files = 20
max_size_mb = 500

[features.audio]
min_decibels = -45
initial_silence_timeout = 3000
silence_timeout = 1500
max_duration = 15000
chunk_duration = 1000
sample_rate = 44100

[UI]
name = "AquaPDF"
description = "Tu asistente AI para políticas y procedimientos de la empresa"
default_collapse_content = true
cot = "full"
custom_css = "public/custom.css"
custom_font = "https://fonts.googleapis.com/css2?family=Sora:wght@400;500;700&display=swap"

[UI.theme]
default = "dark"
font_family = "Sora, sans-serif"

[UI.theme.light]
background = "#FFFFFF"
paper = "#EFEBCE"

[UI.theme.light.primary]
main = "#BB8588"
dark = "#A3A380"
light = "#D8A48F"

[UI.theme.light.text]
primary = "#2D2D2D"
secondary = "#595959"

[UI.theme.dark]
background = "#2D2D2D"
paper = "#363636"

[UI.theme.dark.primary]
main = "#D6CE93"
dark = "#A3A380"
light = "#EFEBCE"

[UI.theme.dark.text]
primary = "#EFEBCE"
secondary = "#D8A48F"

[meta]
generated_by = "1.3.2"
